Repository chiefwigms/picobrew_pico, pull requests merged in 2020-07, with the labels that each got.

#68 ignore ._ metadata files created by macos -> linux file sharing
  app/main/routes_frontend.py
  app/main/session_parser.py
Labels: bug

#70 Picostill Session Support for ZSeries Device Types
  README.md
  app/main/routes_frontend.py
  app/main/routes_zseries_api.py
  app/templates/navbar.html
Labels: enhancement

#69 Readme.md updates
  README.md
Labels: documentation
